# Generated by Django 3.2.13 on 2023-03-05 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Имя датчика')),
                ('type', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Тип датчика')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя события')),
                ('temperature', models.IntegerField(blank=True, default=None, null=True, verbose_name='Температура')),
                ('humidity', models.IntegerField(blank=True, default=None, null=True, verbose_name='Влажность')),
                ('sensor_id', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.PROTECT, to='sensor.sensor', verbose_name='ID датчика')),
            ],
        ),
    ]
